{
 "title": "ARTICLE-SERVER",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "API-CALL",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[$tag_method]-$tag_path",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "article_server_api_request_count",
     "query": "SELECT non_negative_derivative(max(\"counter\"), 1m) FROM \"article_server_api_request_count\" WHERE (\"host\" =~ /.*/) AND $timeFilter GROUP BY time(1m), \"method\", \"path\" fill(0)",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  },
  {
   "title": "API-CALL-LATENCY",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "[$tag_method]-$tag_path",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "method" ], "type": "tag" },
      { "params": [ "path" ], "type": "tag" }
     ],
     "measurement": "article_server_api_request_latency",
     "select": [
      [
       { "params": [ "0.9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*/" }
     ]
    },
    {
     "alias": "TOTAL",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "article_server_api_request_latency",
     "select": [
      [
       { "params": [ "0.9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "hos", "operator": "=~", "value": "/.*/" }
     ]
    }
   ]
  },
  {
   "title": "API-RESPONSE-STATUS",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "alias": "Status-200",
     "measurement": "article_server_api_request_count",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "code", "operator": "=", "value": "200" }
     ]
    },
    {
     "alias": "Status-404",
     "measurement": "article_server_api_request_count",
     "select": [
      [
       { "params": [ "counter" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/.*/" },
      { "condition": "AND", "key": "code", "operator": "=", "value": "404" }
     ]
    }
   ]
  }
 ]
}