-- DROP TABLE IF EXISTS accounts;
-- DROP TABLE IF EXISTS article_tags;
-- DROP TABLE IF EXISTS tags;
-- DROP INDEX idx_comments_deleted_at;
-- DROP TABLE IF EXISTS comments;
-- DROP INDEX idx_articles_deleted_at_unix;
-- DROP TABLE IF EXISTS articles
